"""Typed errors exposed by outbound domain ports."""

from app.domain.errors.auth import (
    AuthConflictError,
    AuthError,
    AuthStoreError,
    InvalidCredentialsError,
    InvalidCsrfTokenError,
    InvalidSessionError,
    PasswordPolicyError,
)
from app.domain.errors.chat import (
    ChatAdmissionError,
    ChatConcurrencyLimitError,
    ChatRateLimitExceededError,
)
from app.domain.errors.conversation import (
    ChatRequestConflictError,
    ChatRequestLeaseLostError,
    ConversationStoreConfigurationError,
    ConversationStoreConnectionError,
    ConversationStoreError,
    ConversationStoreOperationError,
    ConversationStoreProtocolError,
)
from app.domain.errors.kira import (
    KiraAuthenticationError,
    KiraClientError,
    KiraConnectionError,
    KiraHttpError,
    KiraMalformedSseError,
    KiraProtocolError,
    KiraTimeoutError,
)
from app.domain.errors.memory import (
    LongTermMemoryConfigurationError,
    LongTermMemoryConnectionError,
    LongTermMemoryError,
    LongTermMemoryOperationError,
    LongTermMemoryProtocolError,
    LongTermMemoryTimeoutError,
)
from app.domain.errors.memory_job import (
    MemoryJobLeaseLostError,
    MemoryJobQueueConfigurationError,
    MemoryJobQueueConnectionError,
    MemoryJobQueueError,
    MemoryJobQueueOperationError,
    MemoryJobQueueProtocolError,
)
from app.domain.errors.query_rewriter import (
    QueryRewriterConfigurationError,
    QueryRewriterConnectionError,
    QueryRewriterError,
    QueryRewriterHttpError,
    QueryRewriterProtocolError,
    QueryRewriterTimeoutError,
)

__all__ = [
    "ChatAdmissionError",
    "ChatConcurrencyLimitError",
    "ChatRateLimitExceededError",
    "ChatRequestConflictError",
    "ChatRequestLeaseLostError",
    "AuthConflictError",
    "AuthError",
    "AuthStoreError",
    "ConversationStoreConfigurationError",
    "ConversationStoreConnectionError",
    "ConversationStoreError",
    "ConversationStoreOperationError",
    "ConversationStoreProtocolError",
    "KiraAuthenticationError",
    "KiraClientError",
    "KiraConnectionError",
    "KiraHttpError",
    "KiraMalformedSseError",
    "KiraProtocolError",
    "KiraTimeoutError",
    "InvalidCredentialsError",
    "InvalidCsrfTokenError",
    "InvalidSessionError",
    "LongTermMemoryConfigurationError",
    "LongTermMemoryConnectionError",
    "LongTermMemoryError",
    "LongTermMemoryOperationError",
    "LongTermMemoryProtocolError",
    "LongTermMemoryTimeoutError",
    "MemoryJobLeaseLostError",
    "MemoryJobQueueConfigurationError",
    "MemoryJobQueueConnectionError",
    "MemoryJobQueueError",
    "MemoryJobQueueOperationError",
    "MemoryJobQueueProtocolError",
    "PasswordPolicyError",
    "QueryRewriterConfigurationError",
    "QueryRewriterConnectionError",
    "QueryRewriterError",
    "QueryRewriterHttpError",
    "QueryRewriterProtocolError",
    "QueryRewriterTimeoutError",
]
